# Project Constants

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = SCREEN_HEIGHT * 0.03
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_VELOCITY = 1.2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 400
PLAYER_SPEED = 250
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.1

SHOT_RADIUS = 5
