# Project Constants
import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = SCREEN_HEIGHT * 0.03
ASTEROID_BASE_SPAWN_RATE = 0.7  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.1
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 400
PLAYER_SPEED = 280
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.08
PLAYER_SHOT_RADIUS = 5

SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
GAME_CLOCK = pygame.time.Clock()
BG_MENU = pygame.image.load("assets/Background.png")


def get_font(size):  # Returns Press-Start-2P in the desired size
    return pygame.font.Font("assets/font.ttf", size)
